import type { PageBlock, StructuredBrokerSection } from '../components/PageBuilder';
import type { BrokerContent, FAQ, GuideSection } from './types';

export interface LegacySection { heading?: string; paragraphs:string[]; bullets?:string[]; }
let blockIdCounter=0;
function newBlockId():string{blockIdCounter+=1;return `seed-${Date.now()}-${blockIdCounter}`;}
function escapeHtml(s:string):string{return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
function paragraphsToHtml(paragraphs:string[],bullets?:string[]):string{const parts:string[]=[];for(const p of paragraphs){if(p&&p.trim())parts.push(`<p>${escapeHtml(p)}</p>`);}if(bullets?.length){const items=bullets.filter(b=>b&&b.trim());if(items.length)parts.push(`<ul>${items.map(b=>`<li>${escapeHtml(b)}</li>`).join('')}</ul>`);}return parts.join('\n');}
const STRUCTURED_PREFIX='__STRUCTURED_BROKER_DATA__:';
function structuredMarker(heading?:string):{brokerId:number;section:StructuredBrokerSection}|null{if(!heading?.startsWith(STRUCTURED_PREFIX))return null;const [,id,section]=heading.split(':');if(!Number(id)||!['overview','pricing','trust','platforms','features','editorial'].includes(section))return null;return {brokerId:Number(id),section:section as StructuredBrokerSection};}
export function legacySectionsToBlocks(sections:LegacySection[]):PageBlock[]{const blocks:PageBlock[]=[];for(const section of sections){const marker=structuredMarker(section.heading);if(marker){blocks.push({id:newBlockId(),type:'structured_broker_data',brokerId:marker.brokerId,section:marker.section});continue;}const html=paragraphsToHtml(section.paragraphs,section.bullets);if(!html&&!section.heading)continue;if(section.heading)blocks.push({id:newBlockId(),type:'heading',title:section.heading});if(html)blocks.push({id:newBlockId(),type:'richtext',html});}return blocks;}
export function faqsToBlocks(faqs:FAQ[],headingTitle='Frequently asked questions'):PageBlock[]{const real=faqs.filter(f=>f.q?.trim()||f.a?.trim());if(!real.length)return [];const blocks:PageBlock[]=[{id:newBlockId(),type:'heading',title:headingTitle}];for(const f of real)blocks.push({id:newBlockId(),type:'richtext',html:`<p><strong>${escapeHtml(f.q)}</strong></p><p>${escapeHtml(f.a)}</p>`});return blocks;}
export function blocksHaveContent(blocks:unknown[]|undefined|null):boolean{if(!Array.isArray(blocks)||!blocks.length)return false;return blocks.some((raw)=>{const block=raw as Partial<PageBlock>;if(block.type==='richtext')return Boolean(block.html&&block.html.replace(/<[^>]+>/g,'').trim());if(block.type==='heading')return Boolean(block.title&&block.title.trim());return true;});}
const BROKER_FIELD_HEADINGS:[keyof BrokerContent,string,StructuredBrokerSection][]=[
  ['overview','Overview','overview'],['verdict','Our verdict','editorial'],['why_recommend','Why we recommend this broker','editorial'],['best_for_detail','Best for','editorial'],['avoid_if','Consider avoiding if','editorial'],
  ['regulation_detail','Regulation','trust'],['fees_detail','Fees & costs','pricing'],['platform_intro','Trading platforms','platforms'],['accounts_intro','Account types','features'],['funding_intro','Deposits & withdrawals','features'],
];
export function brokerContentToLegacySections(content:BrokerContent|null|undefined):LegacySection[]{if(!content)return [];const sections:LegacySection[]=[];const added=new Set<string>();for(const [field,heading,structuredSection] of BROKER_FIELD_HEADINGS){const paragraphs=(content[field] as string[]|undefined)??[];if(!added.has(structuredSection)){sections.push({heading:`${STRUCTURED_PREFIX}${content.broker_id}:${structuredSection}`,paragraphs:[]});added.add(structuredSection);}if(paragraphs.some(p=>p&&p.trim()))sections.push({heading,paragraphs});}return sections;}
export function guideSectionsToLegacySections(sections:GuideSection[]|undefined|null):LegacySection[]{if(!Array.isArray(sections))return [];return sections.map(s=>({heading:s.heading,paragraphs:s.body??[],bullets:s.bullets}));}
export function introCriteriaToLegacySections(intro:string[]|undefined,criteria:string[]|undefined,sections:{heading:string;body:string[];bullets?:string[]}[]|undefined):LegacySection[]{const out:LegacySection[]=[];if(intro?.some(p=>p&&p.trim()))out.push({paragraphs:intro});if(criteria?.some(p=>p&&p.trim()))out.push({heading:'What to look for',paragraphs:[],bullets:criteria});for(const s of sections??[])out.push({heading:s.heading,paragraphs:s.body??[],bullets:s.bullets});return out;}
export function isBlockShape(sections:unknown):sections is PageBlock[]{if(!Array.isArray(sections)||!sections.length)return false;const first=sections[0] as Record<string,unknown>;return typeof first==='object'&&first!==null&&'type' in first&&'id' in first;}
