import { useMemo, useState } from 'react';
import type { Broker, ContentDocument, CountryPage, Intent } from '../../lib/types';
import CanonicalBestForHub from './CanonicalBestForHub';
import CanonicalEditorLauncher from './CanonicalEditorLauncher';

export default function CanonicalEditorHub({ mode, intents, docs, brokers, countries, token, countrySlug, onSaved }: { mode:'global'|'country'; intents:Intent[]; docs:ContentDocument[]; brokers:Broker[]; countries:CountryPage[]; token:string; countrySlug?:string; onSaved:()=>Promise<void>|void }) {
 const [topic,setTopic]=useState<string|null>(null);
 const map=useMemo(()=>({beginners:'forex-brokers-for-beginners','low-spread':'low-spread-forex-brokers',mt4:'mt4-forex-brokers',mt5:'mt5-forex-brokers',gold:'gold-forex-brokers',scalping:'forex-brokers-for-scalping',islamic:'islamic-forex-brokers',ecn:'ecn-forex-brokers','copy-trading':'copy-trading-forex-brokers','swing-trading':'forex-brokers-for-swing-trading','high-leverage':'high-leverage-forex-brokers'} as Record<string,string>),[]);
 if(topic) return <CanonicalEditorLauncher kind={mode} topicSlug={topic} countrySlug={countrySlug} token={token} brokers={brokers} countries={countries} onClose={()=>setTopic(null)} onSaved={onSaved}/>;
 const rows=intents.filter(i=>map[i.slug]).map(i=>({i,slug:map[i.slug],doc:docs.find(d=>d.content_key===(mode==='global'?`best-for:${i.slug}`:`country-topic:${countrySlug}:${map[i.slug]}`))}));
 return <div className="rounded-2xl border border-line bg-white p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Canonical editor</p><h2 className="mt-1 font-display text-xl font-bold text-ink-950">{mode==='global'?'Global Best-For':'Country Best-For'}</h2><p className="mt-1 text-sm text-slate-500">Edit the canonical PageBuilder document. Legacy /best and /countries/.../best URLs are redirects only.</p></div></div><div className="mt-5 divide-y divide-line overflow-hidden rounded-xl border border-line">{rows.map(({i,slug,doc})=><div key={i.slug} className="flex items-center gap-3 px-4 py-3"><div className="min-w-0 flex-1"><p className="text-sm font-bold text-ink-950">{i.title}</p><p className="text-xs text-slate-400">/{mode==='global'?slug:`${countrySlug}/${slug}`} · {doc?.blocks?.length||0} blocks</p></div><button onClick={()=>setTopic(i.slug)} className="rounded-lg bg-ink-950 px-3 py-2 text-xs font-bold text-white">Edit</button></div>)}</div></div>;
}
