import { useMemo, useState } from 'react';
import type { Broker, ContentDocument, CountryPage, Intent } from '../../lib/types';
import CanonicalEditorLauncher from './CanonicalEditorLauncher';

const MAP: Record<string,string> = { beginners:'forex-brokers-for-beginners','low-spread':'low-spread-forex-brokers',mt4:'mt4-forex-brokers',mt5:'mt5-forex-brokers',gold:'gold-forex-brokers',scalping:'forex-brokers-for-scalping',islamic:'islamic-forex-brokers',ecn:'ecn-forex-brokers','copy-trading':'copy-trading-forex-brokers','swing-trading':'forex-brokers-for-swing-trading','high-leverage':'high-leverage-forex-brokers' };
export default function CanonicalBestForHub({ intents, docs, brokers, countries, token, onSaved }: { intents:Intent[]; docs:ContentDocument[]; brokers:Broker[]; countries:CountryPage[]; token:string; onSaved:()=>Promise<void>|void }) {
 const [editing,setEditing]=useState<string|null>(null);
 const rows=useMemo(()=>intents.map(i=>({intent:i,slug:MAP[i.slug]||i.slug,doc:docs.find(d=>d.content_key===`best-for:${i.slug}`)})).filter(x=>Boolean(MAP[x.intent.slug])),[intents,docs]);
 if(editing) return <CanonicalEditorLauncher kind="global" topicSlug={editing} token={token} brokers={brokers} countries={countries} onClose={()=>setEditing(null)} onSaved={onSaved}/>;
 return <div className="space-y-5"><div className="rounded-2xl border border-line bg-white p-5"><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Canonical Best-For</p><h2 className="mt-1 font-display text-2xl font-bold text-ink-950">Global commercial pages</h2><p className="mt-1 text-sm text-slate-500">The editable owners are the canonical URLs. Legacy /best/* URLs are redirects only.</p></div><div className="overflow-hidden rounded-2xl border border-line bg-white">{rows.map(({intent,slug,doc})=><div key={intent.slug} className="flex items-center gap-3 border-b border-line px-5 py-4 last:border-0"><div className="min-w-0 flex-1"><p className="font-display text-sm font-bold text-ink-950">{intent.title}</p><p className="mt-1 text-xs text-slate-400">/{slug} · {doc?.published?'Published':'Draft'} · {doc?.blocks?.length||0} blocks</p></div><a href={`/${slug}`} target="_blank" rel="noreferrer" className="rounded-lg border border-line px-3 py-2 text-xs font-bold">Preview</a><button onClick={()=>setEditing(intent.slug)} className="rounded-lg bg-ink-950 px-3 py-2 text-xs font-bold text-white">Edit</button></div>)}</div></div>;
}
