import { useEffect, useState } from 'react';
import type { Broker, CountryIntentBrokerRanking, CountryPage, Intent } from '../../lib/types';

export default function RankingManager({ countries,intents,brokers,token }: {countries:CountryPage[];intents:Intent[];brokers:Broker[];token:string}) {
 const [country,setCountry]=useState(''); const [intent,setIntent]=useState(''); const [rows,setRows]=useState<CountryIntentBrokerRanking[]>([]); const [loading,setLoading]=useState(false); const [msg,setMsg]=useState('');
 useEffect(()=>{ if(!country&&countries[0]) setCountry(countries[0].slug); if(!intent&&intents[0]) setIntent(intents[0].slug); },[countries,intents,country,intent]);
 useEffect(()=>{ if(!country||!intent)return; setLoading(true); fetch(`/api/country-intent-rankings?country=${encodeURIComponent(country)}&intent=${encodeURIComponent(intent)}`).then(r=>r.json()).then(x=>setRows(Array.isArray(x)?x:[])).finally(()=>setLoading(false)); },[country,intent]);
 const save=async(r:CountryIntentBrokerRanking, patch:Record<string,unknown>)=>{ const c=countries.find(x=>x.slug===country), i=intents.find(x=>x.slug===intent); if(!c||!i)return; const res=await fetch('/api/country-intent-rankings',{method:'PUT',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({country_id:c.id,intent_id:i.id,broker_id:r.broker_id,force_include:r.force_include,force_exclude:r.force_exclude,manual_rank:r.manual_rank,score_adjustment:r.score_adjustment||0,featured_override:r.featured_override,editorial_note:r.editorial_note,...patch})}); if(res.ok){setMsg('Saved'); const x=await fetch(`/api/country-intent-rankings?country=${country}&intent=${intent}`).then(a=>a.json());setRows(x);} else setMsg('Could not save'); };
 return <section className="rounded-2xl border border-line bg-white p-5"><div className="flex flex-wrap gap-3 items-end"><label className="text-sm font-semibold">Country<select className="mt-1 block rounded-lg border border-line p-2" value={country} onChange={e=>setCountry(e.target.value)}>{countries.map(c=><option key={c.id} value={c.slug}>{c.flag} {c.name}</option>)}</select></label><label className="text-sm font-semibold">Intent<select className="mt-1 block rounded-lg border border-line p-2" value={intent} onChange={e=>setIntent(e.target.value)}>{intents.map(i=><option key={i.id} value={i.slug}>{i.label}</option>)}</select></label><span className="text-xs text-slate-500">{msg}</span></div><p className="mt-3 text-sm text-slate-600">Automatic rankings remain the base. Editorial controls override the final display without changing broker source data.</p><div className="mt-5 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-slate-500"><th>Final</th><th>Broker</th><th>Score</th><th>Manual rank</th><th>Adjust</th><th>Exclude</th><th>Feature</th><th>Note</th></tr></thead><tbody>{loading?<tr><td colSpan={8} className="p-4">Loading…</td></tr>:rows.map(r=><tr key={r.broker_id} className="border-b"><td className="py-3 font-bold">#{r.final_rank}</td><td>{r.broker?.name||brokers.find(b=>b.id===r.broker_id)?.name}</td><td>{Number(r.final_score).toFixed(1)}</td><td><input className="w-16 rounded border p-1" type="number" value={r.manual_rank??''} onChange={e=>save(r,{manual_rank:e.target.value===''?null:Number(e.target.value)})}/></td><td><input className="w-16 rounded border p-1" type="number" value={r.score_adjustment||0} onChange={e=>save(r,{score_adjustment:Number(e.target.value)})}/></td><td><input type="checkbox" checked={!!r.force_exclude} onChange={e=>save(r,{force_exclude:e.target.checked,force_include:false})}/></td><td><input type="checkbox" checked={!!r.featured} onChange={e=>save(r,{featured_override:e.target.checked})}/></td><td><input className="min-w-48 rounded border p-1" defaultValue={r.editorial_note||''} onBlur={e=>save(r,{editorial_note:e.target.value})}/></td></tr>)}</tbody></table></div></section>
}
