import { useCallback, useEffect, useState } from 'react';
import { ChevronLeft, Loader2, LogOut, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import type { Session } from '@supabase/supabase-js';
import type { Broker, ContentDocument, CountryPage, Intent } from '../lib/types';
import supabase from '../lib/supabase';
import CanonicalEditorIndex from '../components/admin/CanonicalEditorIndex';
import CanonicalBrokerWorkspace from '../components/admin/CanonicalBrokerWorkspace';
import GuideContentEditor from '../components/admin/GuideContentEditor';

function AuthLoading(){return <div className="flex min-h-screen items-center justify-center bg-paper"><Loader2 className="animate-spin text-emerald-600" size={30}/></div>}

function GuideWorkspace({docs,brokers,token,onSaved}:{docs:ContentDocument[];brokers:Broker[];token:string;onSaved:()=>Promise<void>}){
 const [doc,setDoc]=useState<ContentDocument|null>(null);
 const guideDocs=docs.filter(d=>d.content_type==='guide'||d.content_type==='country-guide');
 return <div className="rounded-2xl border border-line bg-white p-5"><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Guide editor</p><h2 className="mt-1 font-display text-xl font-bold text-ink-950">All guide documents</h2><p className="mt-1 text-sm text-slate-500">Global and country guides use the same visual PageBuilder. Existing guide content is loaded into the editor without replacing the document automatically.</p><div className="mt-5 divide-y divide-line overflow-hidden rounded-xl border border-line">{guideDocs.map(d=><div key={d.id} className="flex items-center gap-3 px-4 py-3"><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-ink-950">{d.title||d.content_key}</p><p className="truncate text-xs text-slate-400">{d.content_type} · {d.country_slug?`/${d.country_slug}`:'global'} · {d.published?'Published':'Draft'} · {d.blocks?.length||0} blocks</p></div><Link to={d.country_slug&&d.slug?`/${d.country_slug}/guides/${d.slug}`:d.slug?`/guides/${d.slug}`:'#'} target="_blank" className="rounded-lg px-2 py-1.5 text-xs font-bold text-slate-500 hover:bg-paper">View</Link><button onClick={()=>setDoc(d)} className="rounded-lg bg-ink-950 px-3 py-2 text-xs font-bold text-white">Edit</button></div>)}{!guideDocs.length&&<p className="p-6 text-sm text-slate-400">No canonical guide documents found.</p>}</div>{doc&&<GuideContentEditor document={doc} brokers={brokers} token={token} onClose={()=>setDoc(null)} onSave={async(next,isNew)=>{const key=next.content_key||doc.content_key;const res=await fetch('/api/content-documents',{method:isNew?'POST':'PUT',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({...next,id:isNew?undefined:doc.id,content_key:key,content_type:doc.content_type,country_slug:doc.country_slug,topic_slug:doc.topic_slug,slug:next.slug||doc.slug})});const out=await res.json().catch(()=>({}));if(!res.ok)throw new Error(out.error||'Could not save guide');await onSaved();setDoc(null)}}/>}</div>
}

export default function AdminCanonicalWorkspace(){
 const [session,setSession]=useState<Session|null>(null);const [role,setRole]=useState('checking');const [loading,setLoading]=useState(true);const [tab,setTab]=useState<'broker'|'global'|'country'|'guides'>('broker');
 const [brokers,setBrokers]=useState<Broker[]>([]);const [intents,setIntents]=useState<Intent[]>([]);const [countries,setCountries]=useState<CountryPage[]>([]);const [docs,setDocs]=useState<ContentDocument[]>([]);const [error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);try{const [b,i,c,d]=await Promise.all([fetch('/api/brokers').then(r=>r.json()),fetch('/api/intents').then(r=>r.json()),fetch('/api/countries').then(r=>r.json()),fetch('/api/content-documents').then(r=>r.json())]);setBrokers(Array.isArray(b)?b:[]);setIntents(Array.isArray(i)?i:[]);setCountries(Array.isArray(c)?c:[]);setDocs(Array.isArray(d)?d:[]);setError('')}catch(e){setError(e instanceof Error?e.message:'Could not load CMS data')}finally{setLoading(false)}},[]);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);if(!data.session){setRole('none');return;}fetch('/api/admin-users?self=1',{headers:{Authorization:`Bearer ${data.session.access_token}`}}).then(r=>r.ok?r.json():{role:null}).then(d=>setRole(d.role??'none')).catch(()=>setRole('none'))});const {data:sub}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(s)fetch('/api/admin-users?self=1',{headers:{Authorization:`Bearer ${s.access_token}`}}).then(r=>r.ok?r.json():{role:null}).then(d=>setRole(d.role??'none')).catch(()=>setRole('none'));else setRole('none')});return()=>sub.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session&&role!=='none'&&role!=='checking')load()},[session,role,load]);
 if(!session||role==='none')return <div className="flex min-h-screen items-center justify-center bg-paper"><div className="rounded-2xl border border-line bg-white p-7 text-center"><p className="font-display text-xl font-bold text-ink-950">Admin access required</p><p className="mt-2 text-sm text-slate-500">Sign in through the main admin console first.</p><Link to="/archypage" className="mt-4 inline-flex rounded-xl bg-ink-950 px-4 py-2.5 text-sm font-bold text-white">Open admin</Link></div></div>;
 if(role==='checking'||loading)return <AuthLoading/>;
 const tabs=[['broker','Broker'],['global','Global Best-For'],['country','Country Best-For'],['guides','Guides']] as const;
 return <div className="min-h-screen bg-paper"><header className="sticky top-0 z-50 border-b border-line bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center gap-3 px-4 py-3 sm:px-6"><Link to="/archypage" className="rounded-lg p-2 text-slate-400 hover:bg-paper"><ChevronLeft size={18}/></Link><div className="min-w-0 flex-1"><p className="font-display text-lg font-bold text-ink-950">PipRank Canonical CMS</p><p className="text-xs text-slate-400">Broker, Best-For and Guide PageBuilder editors</p></div><button onClick={()=>supabase.auth.signOut()} className="rounded-lg p-2 text-slate-400 hover:bg-paper hover:text-rose-600"><LogOut size={17}/></button></div><div className="mx-auto flex max-w-7xl gap-1 overflow-x-auto px-4 pb-2 sm:px-6">{tabs.map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`whitespace-nowrap rounded-lg px-3.5 py-2 text-xs font-bold ${tab===key?'bg-ink-950 text-white':'text-slate-500 hover:bg-paper'}`}>{label}</button>)}</div></header><main className="mx-auto max-w-7xl px-4 py-7 sm:px-6">{error&&<div className="mb-5 rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-600">{error}</div>}{tab==='broker'&&<CanonicalBrokerWorkspace brokers={brokers} token={session.access_token} onSaved={load}/>} {tab==='global'&&<CanonicalEditorIndex mode="global" intents={intents} docs={docs} brokers={brokers} countries={countries} token={session.access_token} onSaved={load}/>} {tab==='country'&&<CanonicalEditorIndex mode="country" intents={intents} docs={docs} brokers={brokers} countries={countries} token={session.access_token} onSaved={load}/>} {tab==='guides'&&<GuideWorkspace docs={docs} brokers={brokers} token={session.access_token} onSaved={load}/>}</main></div>;
}
