import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Check, Compass, Copy, Gauge, GraduationCap, MonitorSmartphone, Percent, Sparkles, Timer, Waves, Zap, type LucideIcon } from 'lucide-react';
import type { Broker, ContentDocument, CountryBestFor, CountryPage, FAQ, Intent, LocalizedSeoPage } from '../lib/types';
import type { CanonicalRoute } from '../lib/canonicalHub/types';
import { fetchBrokers, fetchCountries, fetchCountry, fetchCountryBestFor, fetchCountryBestFors, fetchCountryIntentRankings, fetchIntent, fetchLocalizedSeoPage, fetchLocalizationUiPack } from '../lib/api';
import { fetchPublishedContentDocument, fetchPublishedContentDocumentById, fetchPublishedContentDocuments } from '../lib/canonicalContent';
import PageBlocksRenderer from './PageBlocksRenderer';
import BrokerCard from './BrokerCard';
import Reveal from './Reveal';
import Monogram from './Monogram';
import NewsletterForm from './NewsletterForm';
import { ButtonLink } from './Button';
import NotFound from '../pages/NotFound';
import { useSEO } from '../hooks/useSEO';
import { absoluteUrl, bestForPath, buildBreadcrumbJsonLd, buildFAQPageJsonLd, buildItemListJsonLd, buildWebPageJsonLd, countryBestForSeo, guideSeo, intentSeo, type SeoInput } from '../lib/seo';
import { reviewerFor } from '../lib/team';
import { englishAlternatePath, englishHreflangForCountry, getLocalizationUi, mergeLocalizationUi, type LocalizationUiStrings } from '../lib/localization';
import { fmtMoney } from '../lib/format';
import { allInCost } from '../lib/score';
import { isBlockShape } from '../lib/contentBlocks';
import { useGeo } from '../lib/GeoContext';
import { track } from '../lib/track';

 type Props = { route: CanonicalRoute };
 type Faq = FAQ;

function settingsOf(doc: ContentDocument | null): Record<string, any> { return (doc?.settings ?? {}) as Record<string, any>; }
function faqsOf(doc: ContentDocument | null): Faq[] { const faqs = settingsOf(doc).faqs; return Array.isArray(faqs) ? faqs.filter((x: any) => x?.q && x?.a) : []; }
function linksOf(doc: ContentDocument | null): { label: string; href: string }[] { const links = settingsOf(doc).internalLinks; return Array.isArray(links) ? links.filter((x: any) => x?.label && x?.href) : []; }
function Loading() { return <div className="mx-auto max-w-5xl px-4 py-12 sm:px-6"><div className="h-64 animate-pulse rounded-3xl border border-line bg-white"/><div className="mt-8 h-64 animate-pulse rounded-3xl border border-line bg-white"/></div>; }
function Missing({ countryGuide = false }: { countryGuide?: boolean }) { return countryGuide ? <div className="mx-auto max-w-2xl px-4 py-28 text-center sm:px-6"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-ink-950 text-emerald-400"><Compass size={30}/></div><h1 className="mt-6 font-display text-2xl font-bold text-ink-900">This guide isn't published</h1><p className="mt-3 text-slate-500">It may have moved, been retired, or never existed for this country.</p><ButtonLink variant="dark" size="lg" to="/countries" className="mt-7">Browse countries</ButtonLink></div> : <NotFound/>; }

function EditorialBlocks({ doc, brokers, intent, countrySlug }: { doc: ContentDocument | null; brokers: Broker[]; intent?: string; countrySlug?: string }) {
  if (!doc) return null;
  if (isBlockShape(doc.blocks)) return <PageBlocksRenderer blocks={doc.blocks as any} brokers={brokers} intent={intent} countrySlug={countrySlug} className="piprank-rich-content space-y-8"/>;
  if (doc.html) return <div className="piprank-rich-content" dangerouslySetInnerHTML={{ __html: doc.html }}/>;
  return null;
}

function GuideIndex() {
  const [guides, setGuides] = useState<ContentDocument[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { fetchPublishedContentDocuments({ type: 'guide' }).then(rows => setGuides(rows.filter(g => !g.country_slug))).finally(() => setLoading(false)); }, []);
  useSEO({ title: 'Forex Trading Guides | PipRank', description: 'Forex trading guides covering brokers, costs, risk and trading mechanics.', path: '/guides', type: 'website' }, guides.length ? [buildItemListJsonLd('Forex trading guides', guides.map(g => ({ name: g.title, path: `/guides/${g.slug}` })))] : undefined);
  if (loading) return <Loading/>;
  return <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6"><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">PipRank Guides</p><h1 className="mt-2 font-display text-4xl font-bold tracking-tight text-ink-900">Forex <em className="serif-accent text-emerald-700">trading guides</em></h1><p className="mt-3 max-w-2xl text-slate-500">Research-desk guides covering the foundations, costs, risk and mechanics of forex trading.</p><div className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{guides.map(g => <Link key={g.slug} to={`/guides/${g.slug}`} className="group overflow-hidden rounded-2xl border border-line bg-white"><img src={String(settingsOf(g).image ?? '')} alt={g.title} className="aspect-[16/9] w-full object-cover" loading="lazy"/><div className="p-5"><p className="text-[10px] font-bold uppercase tracking-wide text-emerald-700">{String(settingsOf(g).category ?? 'Basics')}</p><h2 className="mt-1 font-display text-lg font-bold text-ink-900 group-hover:text-emerald-700">{g.title}</h2><p className="mt-2 line-clamp-2 text-sm leading-relaxed text-slate-500">{g.excerpt}</p></div></Link>)}</div></div>;
}

function GuideView({ route, localized = false }: Props & { localized?: boolean }) {
  const [doc, setDoc] = useState<ContentDocument | null>(route.document ?? null); const [brokers, setBrokers] = useState<Broker[]>([]); const [all, setAll] = useState<ContentDocument[]>([]); const [loading, setLoading] = useState(!route.document);
  const countrySlug = route.countrySlug; const locale = route.locale;
  useEffect(() => { Promise.all([doc ? Promise.resolve(doc) : fetchPublishedContentDocument(route.contentKey || (localized ? `localized-guide:${countrySlug}:${route.slug}` : `guide:${route.slug}`)), fetchBrokers(), fetchPublishedContentDocuments({ type: localized ? 'localized-guide' : 'guide' })]).then(([d,b,rows]) => { setDoc(d); setBrokers(b); setAll(rows); }).finally(() => setLoading(false)); }, [route.contentKey, route.slug, countrySlug, localized]);
  const country = useMemo(() => countrySlug ? undefined : null, [countrySlug]);
  const seo = doc ? guideSeo({ ...doc, slug: doc.slug ?? '' }) : null;
  useSEO(seo ? { ...seo, path: route.path, lang: locale } : null, seo ? [buildWebPageJsonLd({ ...seo, path: route.path }), buildBreadcrumbJsonLd([{ name: 'Home', path: '/' }, ...(countrySlug ? [{ name: countrySlug, path: `/${countrySlug}` }] : [{ name: 'Guides', path: '/guides' }]), { name: doc!.title, path: route.path }])] : undefined);
  if (loading) return <Loading/>; if (!doc || !doc.published) return <NotFound/>;
  const related = all.filter(x => x.slug !== doc!.slug).slice(0, 3); const settings = settingsOf(doc); const legacy = Array.isArray(doc.blocks) ? doc.blocks : [];
  return <div className="mx-auto max-w-6xl px-4 py-10 sm:px-6" lang={locale}><nav className="flex gap-1.5 text-xs text-slate-400"><Link to="/">Home</Link><span>/</span>{countrySlug ? <><Link to={`/${countrySlug}`}>{countrySlug}</Link><span>/</span></> : <><Link to="/guides">Guides</Link><span>/</span></>}<span className="text-ink-900">{doc.title}</span></nav><header className="mt-6 rounded-3xl bg-ink-950 p-7 text-white sm:p-10">{settings.image && <img src={String(settings.image)} alt="" className="mb-7 aspect-[21/8] w-full rounded-2xl object-cover"/>}<p className="text-xs font-bold uppercase tracking-widest text-emerald-300">{localized ? `${locale} guide` : 'PipRank Guide'}</p><h1 className="mt-2 font-display text-3xl font-bold sm:text-4xl">{doc.title}</h1>{doc.excerpt && <p className="mt-3 max-w-3xl text-slate-300">{doc.excerpt}</p>}</header><article className="mt-8 rounded-3xl border border-line bg-white p-6 sm:p-9"><EditorialBlocks doc={doc} brokers={brokers} countrySlug={countrySlug}/>{!isBlockShape(doc.blocks) && legacy.map((section: any, i) => <section key={i} className="mt-8"><h2 className="font-display text-2xl font-bold text-ink-900">{section.heading}</h2>{section.body?.map((p: string, j: number) => <p key={j} className="mt-3 text-[15px] leading-7 text-slate-600">{p}</p>)}</section>)}{faqsOf(doc).length > 0 && <section className="mt-10 space-y-3"><h2 className="font-display text-xl font-bold">Frequently asked questions</h2>{faqsOf(doc).map(f => <details key={f.q} className="rounded-2xl border border-line p-5"><summary className="cursor-pointer font-bold">{f.q}</summary><p className="mt-3 text-sm leading-7 text-slate-600">{f.a}</p></details>)}</section>}</article>{related.length > 0 && <section className="mt-10 grid gap-5 sm:grid-cols-3">{related.map(g => <Link key={g.slug} to={localized ? `/${countrySlug}/${locale}/guides/${g.slug}` : `/guides/${g.slug}`} className="rounded-2xl border border-line bg-white p-4"><p className="text-sm font-bold text-ink-900">{g.title}</p></Link>)}</section>}<div className="mt-10"><NewsletterForm/></div></div>;
}

function CountryGuideView({ route }: Props) {
  const [country,setCountry] = useState<CountryPage|null>(null); const [doc,setDoc] = useState<ContentDocument|null>(route.document ?? null); const [brokers,setBrokers] = useState<Broker[]>([]); const [loading,setLoading] = useState(!route.document);
  useEffect(() => { Promise.all([fetchCountry(route.countrySlug!), doc ? Promise.resolve(doc) : fetchPublishedContentDocument(route.contentKey || `country-guide:${route.countrySlug}:${route.slug}`), fetchBrokers()]).then(([c,d,b]) => { setCountry(c); setDoc(d); setBrokers(b); }).finally(() => setLoading(false)); }, [route.countrySlug,route.slug,route.contentKey]);
  const faqs = faqsOf(doc); const links = linksOf(doc); const reviewer = reviewerFor(`${route.countrySlug}-${route.slug}`);
  const seo = country && doc ? { title: doc.seo_title || doc.title, description: doc.seo_description || doc.excerpt, path: route.path, type: 'article' as const } : null;
  useSEO(seo, seo && doc ? [{...buildWebPageJsonLd(seo),author:{'@type':'Person',name:reviewer.penName,jobTitle:reviewer.role,url:absoluteUrl(`/authors#${reviewer.slug}`)}}, buildBreadcrumbJsonLd([{name:'Home',path:'/'},{name:country!.name,path:`/${country!.slug}`},{name:doc!.title,path:route.path}]), ...(faqs.length ? [buildFAQPageJsonLd(faqs.map(f=>({question:f.q,answer:f.a})))] : [])] : undefined);
  if (loading) return <Loading/>; if (!country || !doc || !doc.published) return <Missing countryGuide/>;
  return <div className="mx-auto max-w-5xl px-4 py-12 sm:px-6"><nav className="flex gap-1.5 text-xs text-slate-400"><Link to="/">Home</Link><span>/</span><Link to={`/${country.slug}`}>{country.name}</Link><span>/</span><span className="text-ink-900">{doc.title}</span></nav><p className="mt-6 text-xs font-bold uppercase tracking-widest text-emerald-700">{country.flag} {country.name} guide</p><h1 className="mt-2 font-display text-4xl font-bold text-ink-900">{doc.title}</h1><p className="mt-3 max-w-3xl text-slate-500">{doc.excerpt}</p><article className="mt-8 rounded-3xl border border-line bg-white p-6 sm:p-9"><EditorialBlocks doc={doc} brokers={brokers} countrySlug={country.slug}/>{faqs.length > 0 && <section className="mt-10 space-y-3"><h2 className="font-display text-xl font-bold">Frequently asked questions</h2>{faqs.map(f=><details key={f.q} className="rounded-2xl border border-line p-5"><summary className="cursor-pointer font-bold">{f.q}</summary><p className="mt-3 text-sm leading-7 text-slate-600">{f.a}</p></details>)}</section>}{links.length > 0 && <section className="mt-10"><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Related pages</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{links.map(l=><Link key={l.href} to={l.href} className="rounded-xl border border-line px-4 py-3 text-sm font-semibold">{l.label}</Link>)}</div></section>}</article></div>;
}

const BEST_ICONS: Record<string,LucideIcon>={beginners:GraduationCap,'low-spread':Percent,mt5:MonitorSmartphone,ecn:Zap,'copy-trading':Copy,scalping:Timer,'swing-trading':Waves,'high-leverage':Gauge,gold:Sparkles,islamic:Sparkles};
function reasonFor(slug:string,b:Broker){switch(slug){case'low-spread':return`${b.spread_eurusd}p EUR/USD · ${allInCost(b)} pips all-in per lot`;case'scalping':return`Scalping allowed · ${b.execution_ms}ms execution · ${b.spread_eurusd}p spread`;case'copy-trading':return b.copy_trading?'Native copy-trading platform':'Copy via third-party signal marketplaces';case'mt5':return`Full MT5 suite · ${b.assets.forex} forex pairs · ${b.uptime}% uptime`;case'ecn':return b.commission_value===0?'ECN-style pricing folded into the spread':`Raw ECN pricing · $${b.commission_value.toFixed(2)}/lot commission`;case'beginners':return`${fmtMoney(b.min_deposit)} minimum · free demo · ${b.support_channels.length} support channels`;case'swing-trading':return`Built for multi-day holds · ${b.max_leverage} leverage`;case'high-leverage':return`Up to ${b.max_leverage} leverage · ${fmtMoney(b.min_deposit)} minimum deposit`;default:return b.tagline;}}
function BestForView({route}:{route:CanonicalRoute}){
  const slug=route.slug??''; const [intent,setIntent]=useState<Intent|null>(null); const [doc,setDoc]=useState<ContentDocument|null>(null); const [brokers,setBrokers]=useState<Broker[]>([]); const [countries,setCountries]=useState<CountryPage[]>([]); const [loading,setLoading]=useState(true); const {country:geoCountry}=useGeo();
  useEffect(()=>{Promise.all([fetchIntent(slug),fetchBrokers(),fetchCountries(),fetchPublishedContentDocument(`best-for:${slug}`)]).then(([i,b,c,d])=>{setIntent(i);setBrokers(b);setCountries(c);setDoc(d);track('intent_view',{intent:i.slug,country:geoCountry?.slug??'global'});}).finally(()=>setLoading(false));},[slug]);
  const ranked=useMemo(()=>intent?brokers.filter(b=>b.best_for.includes(intent.slug)).sort((a,b)=>b.rating-a.rating||b.trust_score-a.trust_score):[],[brokers,intent]); const seo:SeoInput|null=intent?intentSeo(intent):null; useSEO(seo,seo&&intent?[buildBreadcrumbJsonLd([{name:'Home',path:'/'},{name:intent.title,path:route.path}]),buildItemListJsonLd(intent.title,ranked.slice(0,10).map(b=>({name:b.name,path:`/brokers/${b.slug}`}))),...(intent.faqs?.length?[buildFAQPageJsonLd(intent.faqs.map(f=>({question:f.q,answer:f.a})))] : [])]:undefined);
  if(loading||!intent)return <Loading/>;
  const Icon=BEST_ICONS[intent.slug]??Sparkles; const blocks=isBlockShape(doc?.blocks)?doc?.blocks:null;
  return <div className="mx-auto max-w-5xl px-4 py-12 sm:px-6"><header className="relative overflow-hidden rounded-3xl bg-ink-950 p-7 text-white sm:p-10"><div className="absolute inset-0 bg-grid-dark"/><div className="relative"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-emerald-500 text-ink-950"><Icon size={24}/></div><p className="mt-4 text-xs font-bold uppercase tracking-widest text-emerald-300">PipRank</p><h1 className="mt-2 font-display text-3xl font-bold sm:text-4xl">{intent.title}</h1>{intent.intro.map(p=><p key={p} className="mt-3 max-w-3xl text-sm leading-7 text-slate-400">{p}</p>)}</div></header><section className="mt-6 rounded-2xl border border-line bg-white p-6"><p className="text-xs font-bold uppercase tracking-widest text-slate-400">How we ranked this list</p><ul className="mt-3 grid gap-2.5 sm:grid-cols-2">{intent.criteria.map(c=><li key={c} className="flex gap-2 text-sm text-slate-600"><Check size={16} className="mt-0.5 shrink-0 text-emerald-600"/>{c}</li>)}</ul></section><div className="mt-8 grid gap-5 lg:grid-cols-2">{ranked.map((b,i)=><Reveal key={b.slug}><BrokerCard broker={b} rank={i+1} note={reasonFor(intent.slug,b)} intent={intent.slug}/></Reveal>)}</div>{blocks?<section className="mt-10"><EditorialBlocks doc={doc} brokers={brokers} intent={intent.slug}/></section>:intent.sections?.length?<section className="mt-10 space-y-6">{intent.sections.map(s=><section key={s.heading} className="rounded-2xl border border-line bg-white p-6"><h2 className="font-display text-xl font-bold">{s.heading}</h2>{s.body.map(p=><p key={p} className="mt-3 text-sm leading-7 text-slate-600">{p}</p>)}{s.bullets?.length?<ul className="mt-3 list-disc pl-5 text-sm text-slate-600">{s.bullets.map(b=><li key={b}>{b}</li>)}</ul>:null}</section>)}</section>:null}{intent.faqs?.length?<section className="mt-10 space-y-3">{intent.faqs.map(f=><details key={f.q} className="rounded-2xl border border-line bg-white p-5"><summary className="cursor-pointer font-bold">{f.q}</summary><p className="mt-3 text-sm leading-7 text-slate-600">{f.a}</p></details>)}</section>:null}{countries.length>0&&<section className="mt-10 rounded-2xl border border-line bg-white p-6"><p className="text-xs font-bold uppercase tracking-widest text-slate-400">Local versions</p><div className="mt-3 flex flex-wrap gap-2">{countries.slice(0,12).map(c=><Link key={c.slug} to={`/${c.slug}/${route.path.slice(1)}`} className="rounded-full border border-line px-3 py-2 text-xs font-semibold">{c.name}</Link>)}</div></section>}</div>;
}

function LocalizedSeoView({route}:{route:CanonicalRoute}){
  const {countrySlug='',locale='',topicSlug=''}=route; const [page,setPage]=useState<LocalizedSeoPage|null>(null); const [country,setCountry]=useState<CountryPage|null>(null); const [brokers,setBrokers]=useState<Broker[]>([]); const [studio,setStudio]=useState<ContentDocument|null>(null); const [ui,setUi]=useState<LocalizationUiStrings>(()=>getLocalizationUi(locale)); const [loading,setLoading]=useState(true);
  useEffect(()=>{Promise.all([fetchLocalizedSeoPage(countrySlug,locale,topicSlug),fetchCountry(countrySlug),fetchBrokers(),fetchLocalizationUiPack(locale).catch(()=>null)]).then(async([p,c,b,pack])=>{setPage(p);setCountry(c);setBrokers(b);setUi(mergeLocalizationUi(locale,pack?.strings));if(p?.content_document_id)setStudio(await fetchPublishedContentDocumentById(Number(p.content_document_id)));}).finally(()=>setLoading(false));},[countrySlug,locale,topicSlug]);
  const topic=page&&page.topic_key!=='all'?null:null; const ranked=useMemo(()=>{if(!country||!page)return [];return brokers.filter(b=>new Set((country.recommended??[]).map(r=>r.slug)).has(b.slug)).sort((a,b)=>b.rating-a.rating);},[country,page,brokers]); const reviewer=reviewerFor(`${countrySlug}-${locale}-${topicSlug}`); const path=route.path; const englishPath=englishAlternatePath(countrySlug,page?.topic_key); const seo=page?{title:page.meta_title||page.title,description:page.meta_description||page.title,path,type:'website' as const,lang:page.locale||locale,alternates:[{hreflang:page.locale||locale,path},{hreflang:englishHreflangForCountry(countrySlug),path:englishPath},{hreflang:'x-default',path:englishPath}]}:null;
  useSEO(seo,seo?[{...buildWebPageJsonLd(seo),inLanguage:page?.locale||locale,author:{'@type':'Person',name:reviewer.penName,jobTitle:reviewer.role,url:absoluteUrl(`/authors#${reviewer.slug}`)}},buildBreadcrumbJsonLd([{name:ui.home,path:'/'},{name:country?.name??countrySlug,path:`/${countrySlug}`},{name:page!.title,path}]),buildItemListJsonLd(page!.title,ranked.slice(0,10).map(b=>({name:b.name,path:`/brokers/${b.slug}`}))),buildFAQPageJsonLd((page?.faqs??[]).map(f=>({question:f.q,answer:f.a})))] : undefined);
  if(loading)return <Loading/>; if(!page||!country||page.published===false)return <NotFound/>;
  return <main className="mx-auto max-w-5xl px-4 py-12 sm:px-6" lang={page.locale?.split('-')[0]||locale}><nav className="mb-5 flex gap-1.5 text-xs text-slate-400"><Link to="/">{ui.home}</Link><span>/</span><Link to={`/${countrySlug}`}>{country.name}</Link><span>/</span><span className="text-ink-900">{page.title}</span></nav><header className="rounded-3xl bg-ink-950 p-7 text-white sm:p-10"><p className="text-sm font-semibold text-emerald-300">{country.flag} {country.name} · {page.language_native_name||page.language_name}</p><h1 className="mt-4 font-display text-3xl font-bold sm:text-4xl">{page.h1||page.title}</h1>{studio?<div className="mt-5"><EditorialBlocks doc={studio} brokers={brokers} countrySlug={country.slug}/></div>:page.content.split(/\n{2,}/).filter(Boolean).map(p=><p key={p} className="mt-3 max-w-3xl text-sm leading-7 text-slate-400">{p}</p>)}<Link to="/quiz" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-emerald-400 px-4 py-2.5 text-sm font-bold text-ink-950"><Sparkles size={16}/>{ui.findBroker}</Link></header><section className="mt-10"><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">{ui.recommendations}</p><h2 className="mt-1 font-display text-2xl font-bold">{page.title}</h2>{ranked.length?<div className="mt-5 grid gap-5 lg:grid-cols-2">{ranked.slice(0,8).map((b,i)=><Reveal key={b.slug}><BrokerCard broker={b} rank={i+1} countrySlug={countrySlug} note={`Recommended for ${country.name}.`}/></Reveal>)}</div>:<div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm">{ui.insufficientData}</div>}</section>{!studio&&<section className="mt-10 rounded-2xl border border-line bg-white p-6"><h2 className="font-display text-xl font-bold">{ui.methodologyTitle}</h2><ul className="mt-4 space-y-3 text-sm text-slate-600"><li className="flex gap-2"><Check size={17} className="text-emerald-600"/>{ui.methodologyAvailability}</li><li className="flex gap-2"><Check size={17} className="text-emerald-600"/>{ui.methodologyIntent}</li><li className="flex gap-2"><Check size={17} className="text-emerald-600"/>{ui.methodologyAffiliate}</li></ul></section>}{page.faqs?.length?<section className="mt-10 space-y-3">{page.faqs.map(f=><details key={f.q} className="rounded-2xl border border-line bg-white p-5"><summary className="cursor-pointer font-bold">{f.q}</summary><p className="mt-3 text-sm leading-7 text-slate-600">{f.a}</p></details></section>:null}</main>;
}

export default function ContentRenderer({ route }: Props) {
  switch(route.type){
    case 'guide': return route.path === '/guides' ? <GuideIndex/> : <GuideView route={route}/>;
    case 'localized-guide': return <GuideView route={route} localized/>;
    case 'country-guide': return <CountryGuideView route={route}/>;
    case 'global-best-for': return <BestForView route={route}/>;
    case 'localized-seo': return <LocalizedSeoView route={route}/>;
    default: return <NotFound/>;
  }
}
