// Generate a sitemap only for production. Every URL listed must be public,
// indexable and generated by the same canonical routing rules used by the app.

import { createClient } from '@supabase/supabase-js';
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { requireSiteUrlForProduction } from './seo-config.mjs';
import { countrySeoTopics, rankCountryTopicBrokers } from './country-seo-topics.mjs';
import { vietnameseCommercialTopics } from './vietnamese-localization.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DIST = join(__dirname, '..', 'dist');
const MAX_BROKERS_FOR_PAIRS = 12;

const GLOBAL_INTENT_TO_PATH = {
  beginners: '/forex-brokers-for-beginners',
  'low-spread': '/low-spread-forex-brokers',
  mt5: '/mt5-forex-brokers',
  mt4: '/mt4-forex-brokers',
  gold: '/gold-forex-brokers',
  ecn: '/ecn-forex-brokers',
  'copy-trading': '/copy-trading-forex-brokers',
  scalping: '/forex-brokers-for-scalping',
  'swing-trading': '/forex-brokers-for-swing-trading',
  'high-leverage': '/high-leverage-forex-brokers',
};

function escXml(value) {
  return String(value ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;');
}
function cleanDate(value) {
  if (!value) return undefined;
  const d = new Date(value);
  return Number.isNaN(d.getTime()) ? undefined : d.toISOString().slice(0, 10);
}

async function fetchRows(supabase, table, selectWithDate, selectBasic) {
  const first = await supabase.from(table).select(selectWithDate);
  if (!first.error) return first.data ?? [];
  const fallback = await supabase.from(table).select(selectBasic);
  if (fallback.error) throw new Error(`[generate-sitemap] Failed to query "${table}": ${fallback.error.message || JSON.stringify(fallback.error)}`);
  return fallback.data ?? [];
}

async function main() {
  if (process.env.VERCEL_ENV !== 'production') {
    console.log('[generate-sitemap] Non-production build — skipping sitemap generation.');
    return;
  }

  const siteUrl = requireSiteUrlForProduction();
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) throw new Error('NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required for the production sitemap.');
  const supabase = createClient(url, key);

  const staticPaths = ['/', '/brokers', '/countries', '/compare', '/guides', '/methodology', '/quiz', '/tools', '/promotions', '/about', '/authors'];
  const urls = staticPaths.map((loc) => ({ loc, lastmod: undefined }));

  const [brokers, countries, guides, intents, countryBestFors, countryGuides, localizedSeoPages] = await Promise.all([
    fetchRows(supabase, 'brokers', 'slug, rating, updated_at, spread_eurusd, assets, platforms, demo_account, min_deposit, best_for, scalping, islamic_account', 'slug, rating, spread_eurusd, assets, platforms, demo_account, min_deposit, best_for, scalping, islamic_account'),
    fetchRows(supabase, 'countries', 'id, slug, recommended, updated_at', 'id, slug, recommended'),
    fetchRows(supabase, 'guides', 'slug, updated_at', 'slug'),
    fetchRows(supabase, 'intents', 'slug, updated_at', 'slug'),
    fetchRows(supabase, 'country_best_for', 'slug, country_id, indexable, updated_at', 'slug, country_id, indexable'),
    fetchRows(supabase, 'content_documents', 'content_type, country_slug, slug, published, indexable, updated_at', 'content_type, country_slug, slug, published, indexable').catch(() => []),
    fetchRows(supabase, 'localized_seo_pages', 'country_id, language_id, slug, published, indexable, updated_at', 'country_id, language_id, slug, published, indexable').catch(() => []),
  ]);

  for (const broker of brokers ?? []) if (broker.slug) urls.push({ loc: `/brokers/${broker.slug}`, lastmod: cleanDate(broker.updated_at) });
  for (const country of countries ?? []) if (country.slug) urls.push({ loc: `/${country.slug}`, lastmod: cleanDate(country.updated_at) });
  for (const guide of guides ?? []) if (guide.slug) urls.push({ loc: `/guides/${guide.slug}`, lastmod: cleanDate(guide.updated_at) });

  // Global intents are emitted at their canonical root-level paths only.
  for (const intent of intents ?? []) {
    const loc = GLOBAL_INTENT_TO_PATH[intent.slug];
    if (loc) urls.push({ loc, lastmod: cleanDate(intent.updated_at) });
  }

  // Country commercial pages are owned exclusively by the SEO matrix.
  for (const country of countries ?? []) {
    if (!country.slug) continue;
    for (const topic of countrySeoTopics) {
      if (topic.indexable === false) continue;
      const eligible = rankCountryTopicBrokers(brokers ?? [], country, topic);
      if (eligible.length >= (topic.minBrokers ?? 1)) urls.push({ loc: `/${country.slug}/${topic.slug}`, lastmod: cleanDate(country.updated_at) });
    }
  }

  const countrySlugById = new Map((countries ?? []).map((country) => [Number(country.id), country.slug]));
  const { data: languageRows, error: languageError } = await supabase.from('country_languages').select('id, country_id, url_prefix, locale, active');
  if (languageError) throw new Error(`[generate-sitemap] Failed to query country_languages: ${languageError.message || JSON.stringify(languageError)}`);
  const languageById = new Map((languageRows ?? []).map((language) => [Number(language.id), language]));
  const localizedLocs = new Set();

  for (const page of localizedSeoPages ?? []) {
    if (!page.slug || !page.published || !page.indexable) continue;
    const countrySlug = countrySlugById.get(Number(page.country_id));
    const language = languageById.get(Number(page.language_id));
    if (!countrySlug || !language?.active || !language.url_prefix) continue;
    const loc = `/${countrySlug}/${language.url_prefix}/${page.slug}`;
    localizedLocs.add(loc);
    urls.push({ loc, lastmod: cleanDate(page.updated_at) });
  }

  const vietnam = (countries ?? []).find((country) => country.slug === 'vietnam');
  if (vietnam) {
    const recommended = new Set((vietnam.recommended ?? []).map((item) => item?.slug));
    for (const localized of vietnameseCommercialTopics) {
      const loc = `/vietnam/vi/${localized.slug}`;
      if (localizedLocs.has(loc)) continue;
      let eligible = (brokers ?? []).filter((broker) => recommended.has(broker.slug));
      if (localized.englishTopicSlug) {
        const topic = countrySeoTopics.find((item) => item.slug === localized.englishTopicSlug);
        if (!topic) continue;
        eligible = rankCountryTopicBrokers(brokers ?? [], vietnam, topic);
      }
      if (eligible.length >= 1) urls.push({ loc, lastmod: cleanDate(vietnam.updated_at) });
    }
  }

  for (const document of countryGuides ?? []) {
    if (document.content_type !== 'country-guide' || !document.country_slug || !document.slug) continue;
    if (document.published === false || document.indexable === false) continue;
    urls.push({ loc: `/${document.country_slug}/guides/${document.slug}`, lastmod: cleanDate(document.updated_at) });
  }

  // Legacy country_best_for URLs are intentionally excluded. Their canonical
  // destinations are generated above by the country SEO matrix.

  const topBrokers = [...(brokers ?? [])].filter((broker) => broker.slug).sort((a, b) => (b.rating ?? 0) - (a.rating ?? 0)).slice(0, MAX_BROKERS_FOR_PAIRS);
  for (let i = 0; i < topBrokers.length; i++) {
    for (let j = i + 1; j < topBrokers.length; j++) {
      const [a, b] = [topBrokers[i], topBrokers[j]].sort((x, y) => x.slug.localeCompare(y.slug));
      const dates = [a.updated_at, b.updated_at].map(cleanDate).filter(Boolean).sort().reverse();
      urls.push({ loc: `/compare/${a.slug}-vs-${b.slug}`, lastmod: dates[0] });
    }
  }

  const byLoc = new Map();
  for (const entry of urls) {
    const previous = byLoc.get(entry.loc);
    if (!previous || (entry.lastmod || '') > (previous.lastmod || '')) byLoc.set(entry.loc, entry);
  }
  const unique = [...byLoc.values()];
  const body = unique.map((entry) => {
    const lastmod = entry.lastmod ? `\n    <lastmod>${entry.lastmod}</lastmod>` : '';
    return `  <url>\n    <loc>${escXml(siteUrl + entry.loc)}</loc>${lastmod}\n  </url>`;
  }).join('\n');
  writeFileSync(join(DIST, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${body}\n</urlset>\n`, 'utf-8');
  console.log(`[generate-sitemap] Wrote ${unique.length} production URLs.`);
}

main().catch((err) => {
  console.error('[generate-sitemap] ERROR:');
  console.error(err instanceof Error ? err.stack || err.message : String(err));
  process.exit(1);
});
