alter table public.countries add column if not exists status text;
update public.countries set status='published' where status is null;
alter table public.countries alter column status set default 'draft';
alter table public.countries alter column status set not null;
alter table public.countries drop constraint if exists countries_status_check;
alter table public.countries add constraint countries_status_check check (status in ('draft','published','closed'));
create table if not exists public.authors (
 id bigint generated by default as identity primary key,
 slug text not null unique,
 name text not null,
 short_bio text not null default '',
 bio text not null default '',
 role text not null default '',
 expertise text[] not null default '{}',
 photo_url text,
 professional_links jsonb not null default '[]'::jsonb,
 credentials jsonb not null default '[]'::jsonb,
 display_order integer not null default 0,
 published boolean not null default false,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
insert into public.authors (slug,name,short_bio,bio,role,expertise,display_order,published) values
('r-adeyemi','R. Adeyemi','Lead Broker Reviewer','Leads broker onboarding at PipRank: verifying licence status against regulator registers, identifying the specific legal entity behind each account, and writing the regulation sections of our reviews.','Lead Broker Reviewer',array['Regulation & entity verification'],0,true),
('j-okafor','J. Okafor','Trading Costs & Execution Editor','Runs the real-money testing process behind every spread, execution-speed and withdrawal-timing figure published on PipRank, and maintains the trading-cost sections of broker reviews.','Trading Costs & Execution Editor',array['Spreads','Execution','Withdrawal testing'],1,true),
('l-mensah','L. Mensah','Data & Methodology Lead','Maintains the Health Score methodology and the data pipeline behind it — refresh cadence, factor weighting, and keeping scores consistent as broker conditions change.','Data & Methodology Lead',array['Health Score formula & data pipeline'],2,true),
('s-nwachukwu','S. Nwachukwu','Country & Compliance Editor','Covers country-level broker availability, local regulatory context, and the country-specific guides published on PipRank.','Country & Compliance Editor',array['Country-specific availability & regulatory context'],3,true)
on conflict (slug) do nothing;
create index if not exists authors_public_order_idx on public.authors (published,display_order,id);
create index if not exists countries_status_idx on public.countries (status,id);
