-- Atomic, deduplicated helpful votes for public reviews.
create table if not exists public.review_helpful_votes (
  id bigint generated by default as identity primary key,
  review_id bigint not null references public.reviews(id) on delete cascade,
  voter_hash text not null,
  created_at timestamptz not null default now(),
  unique (review_id, voter_hash)
);

create index if not exists review_helpful_votes_review_idx
  on public.review_helpful_votes(review_id);

alter table public.review_helpful_votes enable row level security;

create or replace function public.increment_review_helpful(review_id bigint, voter_hash text default null)
returns public.reviews
language plpgsql
security definer
set search_path = public
as $$
declare
  result public.reviews;
begin
  if review_id is null or review_id <= 0 then
    raise exception 'invalid review id';
  end if;

  if voter_hash is not null and length(voter_hash) between 16 and 128 then
    insert into public.review_helpful_votes(review_id, voter_hash)
    values (review_id, voter_hash)
    on conflict (review_id, voter_hash) do nothing;

    if not found then
      select * into result from public.reviews where id = review_id;
      if result.id is null then raise exception 'review not found'; end if;
      return result;
    end if;
  end if;

  update public.reviews
     set helpful = coalesce(helpful, 0) + 1
   where id = review_id
   returning * into result;

  if result.id is null then raise exception 'review not found'; end if;
  return result;
end;
$$;

revoke all on function public.increment_review_helpful(bigint, text) from public;
grant execute on function public.increment_review_helpful(bigint, text) to service_role;
