-- Admin Hub stability fixes
-- 1) Normalize legacy malformed country Best-For JSON so the editor can safely render it.
-- 2) Add the affiliate-link tables expected by the Commercial Hub and /go/ analytics.

UPDATE public.country_best_for
SET intro = '[]'::jsonb
WHERE intro IS NULL OR jsonb_typeof(intro) <> 'array';

UPDATE public.country_best_for
SET sections = '[]'::jsonb
WHERE sections IS NULL OR jsonb_typeof(sections) <> 'array';

UPDATE public.country_best_for
SET faqs = '[]'::jsonb
WHERE faqs IS NULL OR jsonb_typeof(faqs) <> 'array';

CREATE TABLE IF NOT EXISTS public.affiliate_links (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  broker_id integer NOT NULL REFERENCES public.brokers(id) ON DELETE CASCADE,
  country_code text,
  affiliate_url text NOT NULL,
  direct_url text,
  tracking_params jsonb NOT NULL DEFAULT '{}'::jsonb,
  network text,
  active boolean NOT NULL DEFAULT true,
  cpa_notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT affiliate_links_country_code_check CHECK (country_code IS NULL OR country_code ~ '^[A-Z]{2}$')
);

CREATE UNIQUE INDEX IF NOT EXISTS affiliate_links_broker_country_unique
  ON public.affiliate_links (broker_id, country_code)
  WHERE country_code IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS affiliate_links_broker_global_unique
  ON public.affiliate_links (broker_id)
  WHERE country_code IS NULL;

CREATE INDEX IF NOT EXISTS affiliate_links_broker_idx
  ON public.affiliate_links (broker_id);

CREATE INDEX IF NOT EXISTS affiliate_links_country_idx
  ON public.affiliate_links (country_code)
  WHERE country_code IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.redirect_clicks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  broker_id integer REFERENCES public.brokers(id) ON DELETE SET NULL,
  broker_slug text,
  country text,
  source_page text,
  page_type text,
  best_for_category text,
  comparison_pair text,
  referrer text,
  utm_source text,
  device_type text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS redirect_clicks_created_at_idx
  ON public.redirect_clicks (created_at DESC);
CREATE INDEX IF NOT EXISTS redirect_clicks_broker_idx
  ON public.redirect_clicks (broker_id);

ALTER TABLE public.affiliate_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.redirect_clicks ENABLE ROW LEVEL SECURITY;

-- Server-side API access uses the Supabase service role. No public policies are
-- created because affiliate URLs and CPA notes are private admin data.

NOTIFY pgrst, 'reload schema';
