-- Admin CMS schema synchronization.
-- Adds the fields used by the current admin APIs and creates the broker logo
-- storage/table used by the merged broker-assets endpoint.

ALTER TABLE public.broker_content
  ADD COLUMN IF NOT EXISTS overview jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS verdict jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS why_recommend jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS best_for_detail jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS avoid_if jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS regulation_detail jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS fees_detail jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS platform_intro jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS accounts_intro jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS funding_intro jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS faqs jsonb NOT NULL DEFAULT '[]'::jsonb;

ALTER TABLE public.countries
  ADD COLUMN IF NOT EXISTS seo_title text,
  ADD COLUMN IF NOT EXISTS seo_description text,
  ADD COLUMN IF NOT EXISTS seo_intro jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS seo_sections jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS seo_faqs jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS publishing_state text NOT NULL DEFAULT 'draft';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'countries_publishing_state_check'
      AND conrelid = 'public.countries'::regclass
  ) THEN
    ALTER TABLE public.countries
      ADD CONSTRAINT countries_publishing_state_check
      CHECK (publishing_state IN ('draft','published','closed'));
  END IF;
END $$;

ALTER TABLE public.broker_country_availability
  ADD COLUMN IF NOT EXISTS note text,
  ADD COLUMN IF NOT EXISTS priority integer NOT NULL DEFAULT 0;

-- Keep the current canonical `notes` column in sync with the legacy singular
-- field expected by older admin payloads. The API below uses `notes` as the
-- canonical storage field, but the compatibility column prevents older
-- clients from breaking while deployments roll forward.

CREATE TABLE IF NOT EXISTS public.broker_media (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  broker_id bigint NOT NULL UNIQUE REFERENCES public.brokers(id) ON DELETE CASCADE,
  logo_url text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS broker_media_broker_id_idx
  ON public.broker_media(broker_id);

INSERT INTO storage.buckets (id, name, public)
VALUES ('broker-logos', 'broker-logos', true)
ON CONFLICT (id) DO UPDATE SET public = true;

CREATE OR REPLACE FUNCTION public.touch_broker_media_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_broker_media_updated_at ON public.broker_media;
CREATE TRIGGER trg_broker_media_updated_at
BEFORE UPDATE ON public.broker_media
FOR EACH ROW EXECUTE FUNCTION public.touch_broker_media_updated_at();
