-- PipRank Phase 8F — Vietnam Country × Intent setup
-- Safe first step: derives the Vietnam broker candidate pool from the existing
-- countries.recommended JSON. It does NOT invent broker availability or regulatory claims.
-- Run after Phase 8E global ranking controls.

BEGIN;

-- 1) Ensure Vietnam exists.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.countries WHERE slug='vietnam') THEN
    RAISE EXCEPTION 'Vietnam does not exist in public.countries. Add the country before running this setup.';
  END IF;
END $$;

-- 2) Ensure verification table exists.
CREATE TABLE IF NOT EXISTS public.broker_country_verification (
  id bigint generated by default as identity primary key,
  broker_id bigint NOT NULL REFERENCES public.brokers(id) ON DELETE CASCADE,
  country_id bigint NOT NULL REFERENCES public.countries(id) ON DELETE CASCADE,
  availability_verified boolean NOT NULL DEFAULT false,
  local_authorisation_status text NOT NULL DEFAULT 'not_verified'
    CHECK (local_authorisation_status IN ('authorised','not_authorised','not_applicable','not_verified')),
  client_entity text,
  regulator text,
  affiliate_eligible boolean,
  verification_date date,
  source_url text,
  notes text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (broker_id,country_id)
);

-- 3) Seed Vietnam availability candidates from existing countries.recommended.
-- Handles recommended entries stored either as {"slug":"..."} objects or plain strings.
WITH vietnam AS (
  SELECT id, COALESCE(recommended,'[]'::jsonb) AS recommended
  FROM public.countries
  WHERE slug='vietnam'
), candidate_slugs AS (
  SELECT DISTINCT CASE
    WHEN jsonb_typeof(x.value)='object' THEN x.value->>'slug'
    WHEN jsonb_typeof(x.value)='string' THEN trim(both '"' from x.value::text)
    ELSE NULL END AS slug
  FROM vietnam v CROSS JOIN LATERAL jsonb_array_elements(v.recommended) x(value)
), candidates AS (
  SELECT v.id AS country_id,b.id AS broker_id
  FROM vietnam v
  JOIN candidate_slugs s ON s.slug IS NOT NULL
  JOIN public.brokers b ON b.slug=s.slug
)
INSERT INTO public.broker_country_availability (broker_id,country_id,is_available,status,notes,verified,verified_at)
SELECT broker_id,country_id,true,'available','Vietnam candidate seeded from existing Vietnam recommendation pool; verify current availability before editorial promotion.',false,NULL
FROM candidates
ON CONFLICT (broker_id,country_id) DO NOTHING;

-- 4) Create matching verification rows, explicitly unverified.
INSERT INTO public.broker_country_verification (
  broker_id,country_id,availability_verified,local_authorisation_status,notes
)
SELECT a.broker_id,a.country_id,false,'not_verified',
       'Vietnam candidate pending source verification. This row does not assert availability, local authorisation, client entity or affiliate eligibility.'
FROM public.broker_country_availability a
JOIN public.countries c ON c.id=a.country_id
WHERE c.slug='vietnam'
ON CONFLICT (broker_id,country_id) DO NOTHING;

-- 5) Create all Vietnam country intent pages from the global intent registry.
INSERT INTO public.country_best_for (
  country_id,intent_id,intent_slug,slug,label,title,meta_title,meta_description,h1,introduction,
  content,recommended_brokers,faqs,internal_links,published,indexable,published_at,
  intro,icon,criteria,sections,sort_order
)
SELECT
  c.id,i.id,i.slug,
  CASE i.slug
    WHEN 'beginners' THEN 'best-forex-brokers-for-beginners'
    WHEN 'low-spread' THEN 'best-low-spread-forex-brokers'
    WHEN 'ecn' THEN 'best-ecn-forex-brokers'
    WHEN 'copy-trading' THEN 'best-copy-trading-brokers'
    WHEN 'scalping' THEN 'best-forex-brokers-for-scalping'
    WHEN 'swing-trading' THEN 'best-forex-brokers-for-swing-trading'
    WHEN 'high-leverage' THEN 'best-high-leverage-forex-brokers'
    ELSE 'best-'||i.slug||'-brokers'
  END,
  CASE WHEN i.slug='beginners' THEN 'Best for Beginners' ELSE COALESCE(i.label,i.slug) END,
  REPLACE(COALESCE(i.title,'Best Forex Brokers (2026)'),' (2026)',' in Vietnam (2026)'),
  REPLACE(COALESCE(i.title,'Best Forex Brokers (2026)'),' (2026)',' in Vietnam (2026)'),
  'Country-specific PipRank recommendations for Vietnam. Rankings are published only when broker availability has been verified.',
  REPLACE(COALESCE(i.title,'Best Forex Brokers'),' (2026)',' in Vietnam (2026)'),
  NULL,
  '{}'::jsonb,'[]'::jsonb,'[]'::jsonb,'[]'::jsonb,
  false,false,NULL,
  '{}'::jsonb,i.icon,COALESCE(i.criteria,'{}'::jsonb),'[]'::jsonb,
  ROW_NUMBER() OVER (ORDER BY i.id)
FROM public.countries c CROSS JOIN public.intents i
WHERE c.slug='vietnam'
ON CONFLICT (country_id,slug) DO UPDATE SET
  intent_id=EXCLUDED.intent_id,
  intent_slug=EXCLUDED.intent_slug,
  label=EXCLUDED.label,
  title=EXCLUDED.title,
  meta_title=EXCLUDED.meta_title,
  meta_description=EXCLUDED.meta_description,
  h1=EXCLUDED.h1,
  updated_at=now();

COMMIT;

-- Verification worklist. Review these candidates and update verification rows before ranking.
SELECT b.slug,b.name,a.status,a.is_available,v.availability_verified,
       v.local_authorisation_status,v.affiliate_eligible,v.source_url
FROM public.broker_country_availability a
JOIN public.countries c ON c.id=a.country_id
JOIN public.brokers b ON b.id=a.broker_id
LEFT JOIN public.broker_country_verification v ON v.broker_id=a.broker_id AND v.country_id=a.country_id
WHERE c.slug='vietnam'
ORDER BY b.name;
