-- PipRank Phase 11 — Rich Content Studio
-- Run once in Supabase SQL Editor.

create table if not exists public.content_documents (
  id bigint generated by default as identity primary key,
  content_key text not null unique,
  content_type text not null default 'page',
  country_slug text,
  topic_slug text,
  slug text,
  title text not null default '',
  excerpt text not null default '',
  html text not null default '',
  blocks jsonb not null default '[]'::jsonb,
  seo_title text,
  seo_description text,
  indexable boolean not null default true,
  published boolean not null default true,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists content_documents_country_idx on public.content_documents(country_slug);
create index if not exists content_documents_topic_idx on public.content_documents(topic_slug);
create index if not exists content_documents_type_idx on public.content_documents(content_type);

create or replace function public.touch_content_documents_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_content_documents_updated_at on public.content_documents;
create trigger trg_content_documents_updated_at
before update on public.content_documents
for each row execute function public.touch_content_documents_updated_at();

-- The app reads/writes this table through the server-side Supabase service key.
-- Keep browser access disabled unless you deliberately add RLS policies later.
alter table public.content_documents enable row level security;


-- Public bucket used for editorial images inserted into rich content.
insert into storage.buckets (id, name, public)
values ('content-media', 'content-media', true)
on conflict (id) do update set public = true;
