-- PipRank Phase 16: Admin-managed Country × Language localization
create table if not exists public.country_languages (
  id bigint generated by default as identity primary key,
  country_id bigint not null references public.countries(id) on delete cascade,
  name text not null,
  native_name text not null,
  code text not null,
  locale text not null,
  url_prefix text not null,
  is_default boolean not null default false,
  active boolean not null default true,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(country_id, code),
  unique(country_id, url_prefix)
);

create table if not exists public.localized_seo_pages (
  id bigint generated by default as identity primary key,
  country_id bigint not null references public.countries(id) on delete cascade,
  language_id bigint not null references public.country_languages(id) on delete cascade,
  topic_key text not null,
  slug text not null,
  title text not null,
  meta_title text,
  meta_description text,
  h1 text,
  content text not null default '',
  faqs jsonb not null default '[]'::jsonb,
  indexable boolean not null default false,
  published boolean not null default false,
  workflow_status text not null default 'draft',
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(language_id, topic_key),
  unique(country_id, language_id, slug)
);

alter table public.localized_seo_pages
  add column if not exists workflow_status text not null default 'draft';

alter table public.localized_seo_pages
  add column if not exists content_document_id bigint references public.content_documents(id) on delete set null;

create index if not exists country_languages_country_idx
  on public.country_languages(country_id);

create index if not exists localized_seo_pages_lookup_idx
  on public.localized_seo_pages(country_id, language_id, published, indexable);

create index if not exists localized_seo_pages_content_doc_idx
  on public.localized_seo_pages(content_document_id);

-- Admin-editable UI chrome packs per language code.
create table if not exists public.localization_ui_packs (
  id bigint generated by default as identity primary key,
  language_code text not null unique,
  strings jsonb not null default '{}'::jsonb,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Admin-managed preferred translation terms. Keep the column names aligned
-- with the API and LocalizationManager: term_en / term_local.
create table if not exists public.localization_glossary (
  id bigint generated by default as identity primary key,
  language_code text not null,
  term_en text not null,
  term_local text not null,
  notes text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(language_code, term_en)
);

create index if not exists localization_glossary_lang_idx
  on public.localization_glossary(language_code);

-- Safe upgrade for databases that were created from the duplicate glossary
-- definition used in an earlier Phase 16 draft.
alter table public.localization_glossary
  add column if not exists term_en text;
alter table public.localization_glossary
  add column if not exists term_local text;

-- If an older installation used source_term/preferred_term, copy those values
-- into the canonical API columns before enforcing the API's unique key.
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='localization_glossary' and column_name='source_term'
  ) then
    execute 'update public.localization_glossary set term_en = coalesce(term_en, source_term) where term_en is null';
  end if;
  if exists (
    select 1 from information_schema.columns
    where table_schema='public' and table_name='localization_glossary' and column_name='preferred_term'
  ) then
    execute 'update public.localization_glossary set term_local = coalesce(term_local, preferred_term) where term_local is null';
  end if;
end $$;

-- Ensure new localized pages can never be published/indexed accidentally by
-- a language-creation workflow. Publication is an explicit editorial step.
create or replace function public.enforce_localized_page_workflow()
returns trigger
language plpgsql
as $$
begin
  if new.workflow_status <> 'published' then
    new.published := false;
    new.indexable := false;
  end if;
  return new;
end;
$$;

drop trigger if exists localized_page_workflow_guard on public.localized_seo_pages;
create trigger localized_page_workflow_guard
before insert or update on public.localized_seo_pages
for each row execute function public.enforce_localized_page_workflow();

-- Country closure is a hard publishing boundary. Closing a country removes
-- its child SEO surfaces from the index, but does not delete their content.
create or replace function public.cascade_country_closure()
returns trigger
language plpgsql
as $$
begin
  if new.publishing_state = 'closed' and coalesce(old.publishing_state, '') <> 'closed' then
    update public.country_best_for
      set indexable = false
      where country_id = new.id;

    update public.localized_seo_pages
      set published = false,
          indexable = false,
          workflow_status = case when workflow_status = 'published' then 'draft' else workflow_status end
      where country_id = new.id;

    update public.content_documents
      set published = false,
          indexable = false
      where country_slug = new.slug;
  end if;
  return new;
end;
$$;

drop trigger if exists country_closure_guard on public.countries;
create trigger country_closure_guard
after update of publishing_state on public.countries
for each row execute function public.cascade_country_closure();
