-- PipRank Phase 8 Ghana: broker verification layer
-- Run after PHASE-8-GHANA-COMMERCIAL-TOPICAL.sql.
-- This migration does NOT infer Ghana eligibility from affiliate GEO lists alone.
-- Only rows with verified=true should be promoted into Ghana recommendations.

BEGIN;

CREATE TABLE IF NOT EXISTS public.broker_country_verification (
  id bigint generated by default as identity primary key,
  broker_id bigint NOT NULL REFERENCES public.brokers(id) ON DELETE CASCADE,
  country_id bigint NOT NULL REFERENCES public.countries(id) ON DELETE CASCADE,
  availability_verified boolean NOT NULL DEFAULT false,
  local_authorisation_status text NOT NULL DEFAULT 'not_verified'
    CHECK (local_authorisation_status IN ('authorised','not_authorised','not_applicable','not_verified')),
  client_entity text,
  regulator text,
  affiliate_eligible boolean,
  verification_date date,
  source_url text,
  notes text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (broker_id, country_id)
);

CREATE INDEX IF NOT EXISTS idx_broker_country_verification_country
  ON public.broker_country_verification(country_id);
CREATE INDEX IF NOT EXISTS idx_broker_country_verification_broker
  ON public.broker_country_verification(broker_id);

-- Pepperstone: explicit Ghana availability is supported by its official affiliate documentation.
-- We intentionally leave Ghana local authorisation and client entity unverified here.
DO $$
DECLARE ghana_id bigint; broker_id bigint;
BEGIN
  SELECT id INTO ghana_id FROM public.countries WHERE slug='ghana' LIMIT 1;
  SELECT id INTO broker_id FROM public.brokers WHERE slug='pepperstone' LIMIT 1;
  IF ghana_id IS NOT NULL AND broker_id IS NOT NULL THEN
    INSERT INTO public.broker_country_verification (
      broker_id, country_id, availability_verified, local_authorisation_status,
      affiliate_eligible, verification_date, source_url, notes
    ) VALUES (
      broker_id, ghana_id, true, 'not_verified', true, CURRENT_DATE,
      'https://partnership.pepperstone.com/en/affiliates-program/',
      'Official Pepperstone affiliate documentation explicitly includes Ghana. This record does not assert Ghana local regulatory authorisation; verify the client entity and applicable regulator before publishing a local-regulation claim.'
    )
    ON CONFLICT (broker_id, country_id) DO UPDATE SET
      availability_verified=EXCLUDED.availability_verified,
      affiliate_eligible=EXCLUDED.affiliate_eligible,
      verification_date=EXCLUDED.verification_date,
      source_url=EXCLUDED.source_url,
      notes=EXCLUDED.notes,
      updated_at=now();
  END IF;
END $$;

-- Rebuild Ghana's country recommendations from VERIFIED availability only.
DO $$
DECLARE ghana_id bigint;
BEGIN
  SELECT id INTO ghana_id FROM public.countries WHERE slug='ghana' LIMIT 1;
  IF ghana_id IS NULL THEN RETURN; END IF;

  UPDATE public.countries c
  SET recommended = COALESCE((
    SELECT jsonb_agg(
      jsonb_build_object(
        'slug', b.slug,
        'note', 'Ghana availability verified; confirm the current client entity and terms before depositing.'
      ) ORDER BY b.rating DESC NULLS LAST, b.name
    )
    FROM public.broker_country_availability a
    JOIN public.brokers b ON b.id=a.broker_id
    JOIN public.broker_country_verification v
      ON v.broker_id=a.broker_id AND v.country_id=a.country_id
    WHERE a.country_id=ghana_id
      AND a.status='available'
      AND v.availability_verified=true
  ), '[]'::jsonb)
  WHERE c.id=ghana_id;
END $$;

-- Only verified brokers can make Ghana Best-For pages indexable.
UPDATE public.country_best_for cbf
SET indexable = CASE
  WHEN cbf.country_id = (SELECT id FROM public.countries WHERE slug='ghana' LIMIT 1)
  THEN (
    SELECT count(*) >= 2
    FROM public.broker_country_availability a
    JOIN public.broker_country_verification v
      ON v.broker_id=a.broker_id AND v.country_id=a.country_id
    WHERE a.country_id=cbf.country_id
      AND a.status='available'
      AND v.availability_verified=true
  )
  ELSE cbf.indexable
END
WHERE cbf.country_id=(SELECT id FROM public.countries WHERE slug='ghana' LIMIT 1);

COMMIT;
