-- PipRank Phase 16: Admin-managed Country × Language localization
create table if not exists public.country_languages (
  id bigint generated by default as identity primary key,
  country_id bigint not null references public.countries(id) on delete cascade,
  name text not null,
  native_name text not null,
  code text not null,
  locale text not null,
  url_prefix text not null,
  is_default boolean not null default false,
  active boolean not null default true,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(country_id, code),
  unique(country_id, url_prefix)
);

create table if not exists public.localized_seo_pages (
  id bigint generated by default as identity primary key,
  country_id bigint not null references public.countries(id) on delete cascade,
  language_id bigint not null references public.country_languages(id) on delete cascade,
  topic_key text not null,
  slug text not null,
  title text not null,
  meta_title text,
  meta_description text,
  h1 text,
  content text not null default '',
  faqs jsonb not null default '[]'::jsonb,
  indexable boolean not null default false,
  published boolean not null default false,
  workflow_status text not null default 'draft',
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(language_id, topic_key),
  unique(country_id, language_id, slug)
);

-- Safe upgrade for existing deployments
alter table public.localized_seo_pages
  add column if not exists workflow_status text not null default 'draft';

create index if not exists country_languages_country_idx on public.country_languages(country_id);
create index if not exists localized_seo_pages_lookup_idx on public.localized_seo_pages(country_id, language_id, published, indexable);

-- Existing projects use server-side Supabase service credentials for these API writes.
-- Keep these tables out of client-side direct access unless you already have RLS
-- policies that intentionally expose them.

-- UI chrome packs (admin-editable per language code)
create table if not exists public.localization_ui_packs (
  id bigint generated by default as identity primary key,
  language_code text not null unique,
  strings jsonb not null default '{}'::jsonb,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Translation glossary / preferred terms
create table if not exists public.localization_glossary (
  id bigint generated by default as identity primary key,
  language_code text not null,
  term_en text not null,
  term_local text not null,
  notes text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(language_code, term_en)
);

create index if not exists localization_glossary_lang_idx on public.localization_glossary(language_code);

-- UI chrome string packs per language code (admin-editable)
create table if not exists public.localization_ui_packs (
  id bigint generated by default as identity primary key,
  language_code text not null unique,
  strings jsonb not null default '{}'::jsonb,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Translation glossary / preferred terms per language
create table if not exists public.localization_glossary (
  id bigint generated by default as identity primary key,
  language_code text not null,
  source_term text not null,
  preferred_term text not null,
  notes text,
  updated_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(language_code, source_term)
);

create index if not exists localization_glossary_lang_idx on public.localization_glossary(language_code);


-- Option B: link localized commercial pages to Content Studio documents for rich body HTML
alter table public.localized_seo_pages
  add column if not exists content_document_id bigint references public.content_documents(id) on delete set null;

create index if not exists localized_seo_pages_content_doc_idx
  on public.localized_seo_pages(content_document_id);
